const express = require('express')
const dotenv=require('dotenv').config()
const {errorHandler} = require("./middleware/errorMiddleware")
const connectToDatabase = require('./config/db')
const routerApi = require('./routes/main.routes')
const { checkApiKey } = require('./middleware/auth.handler')
const jwtStrategy = require('./services/strategies/jwt.strategy')
const passport = require('passport')

const app = express()
const port = process.env.PORT || 3000

connectToDatabase()
app.use(express.Router())
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use(passport.initialize())
passport.use(jwtStrategy)
app.use(errorHandler)
app.use(checkApiKey)
routerApi(app)
app.listen(port, ()=> {console.log(`Server is runing on port ${port}`)})
